### ISSUE TITLE
Scene info fetch successful, browser does nothing

### ISSUE THREAD

**Issue by jimz011** [porn-vault/plugins#155]
I recently installed some plugins and I can't get this plugin to work correctly. If I run the plugin manually in PV the logs show it is fetching the scene title and gets results. The log shows I should press Y/N in some cases or choose a number from 0 to 9. But in the browser nothing pops up to enter the value, it just keeps showing the loading indicator and does that for a minute or so and then nothing happens.

I can read the full title and descriptions and such being found in the logs, but there is no way to interact with it. Any help would be appreciated.

**Comment by leadwolf** [comment]
You can't interact with plugins from the browser at the moment. The only way is through the console with which you launched the server.

**Comment by jimz011** [comment]
Ah I see, unfortunately I use Unraid and I can't seem to open the original console. Thanks for your time and answers anyway.

**Comment by leadwolf** [comment]
You can disable manual touch. Obviously you won't be able to interact with the plug-in, but at least it won't be blocked
